import 'dart:convert';
import 'package:crypto/crypto.dart';
import 'package:flutter/material.dart';
import 'package:flutter_localizations/flutter_localizations.dart';
import 'package:flutter_svg/flutter_svg.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:url_launcher/url_launcher.dart';

void main()=>runApp(const MirathApp());
String hp(String s)=>sha256.convert(utf8.encode(s)).toString();

class User{String username,name,role,password;User({required this.username,required this.name,required this.role,required this.password});Map<String,dynamic> j()=>{'username':username,'name':name,'role':role,'password':password};factory User.from(Map<String,dynamic>x)=>User(username:'${x['username']??''}',name:'${x['name']??''}',role:'${x['role']??'مشاور'}',password:'${x['password']??''}');}
class Property{String code,type,title,address,owner,phone,price,area,rooms,year,link,desc,agent;Property({required this.code,required this.type,required this.title,required this.address,required this.owner,required this.phone,required this.price,required this.area,required this.rooms,required this.year,required this.link,required this.desc,required this.agent});Map<String,dynamic> j()=>{'code':code,'type':type,'title':title,'address':address,'owner':owner,'phone':phone,'price':price,'area':area,'rooms':rooms,'year':year,'link':link,'desc':desc,'agent':agent};factory Property.from(Map<String,dynamic>x)=>Property(code:'${x['code']??''}',type:'${x['type']??'آپارتمان'}',title:'${x['title']??''}',address:'${x['address']??''}',owner:'${x['owner']??''}',phone:'${x['phone']??''}',price:'${x['price']??''}',area:'${x['area']??''}',rooms:'${x['rooms']??''}',year:'${x['year']??''}',link:'${x['link']??''}',desc:'${x['desc']??''}',agent:'${x['agent']??''}');}
final props=<Property>[];final clients=<String>[];final meetings=<String>[];User? me;
bool get manager=>me?.role=='مدیر'||me?.role=='مدیر فروش';

class DB{static const u='users5',p='props5',c='clients5',m='meetings5',d='dark5';static Future<SharedPreferences> get s=>SharedPreferences.getInstance();static Future<List<User>> users()async{final x=await s;final raw=x.getString(u);if(raw==null){final a=[User(username:'admin',name:'مهندس مجتبی صفری',role:'مدیر',password:hp('1234')),User(username:'sales',name:'خانم طهماسبی پور',role:'مدیر فروش',password:hp('1234')),User(username:'moshaver1',name:'مشاور اول',role:'مشاور',password:hp('1234'))];await saveUsers(a);return a;}return(jsonDecode(raw)as List).map((e)=>User.from(Map<String,dynamic>.from(e))).toList();}static Future<void> saveUsers(List<User>x)async=>(await s).setString(u,jsonEncode(x.map((e)=>e.j()).toList()));static Future<void> load()async{final x=await s;try{props..clear()..addAll((jsonDecode(x.getString(p)??'[]')as List).map((e)=>Property.from(Map<String,dynamic>.from(e))));}catch(_){props.clear();}clients..clear()..addAll(x.getStringList(c)??[]);meetings..clear()..addAll(x.getStringList(m)??[]);}static Future<void> saveProps()async=>(await s).setString(p,jsonEncode(props.map((e)=>e.j()).toList()));static Future<void> saveClients()async=>(await s).setStringList(c,clients);static Future<void> saveMeetings()async=>(await s).setStringList(m,meetings);static Future<bool> dark()async=>(await s).getBool(d)??false;static Future<void> setDark(bool v)async=>(await s).setBool(d,v);}

class MirathApp extends StatefulWidget{const MirathApp({super.key});@override State<MirathApp>createState()=>_App();}
class _App extends State<MirathApp>{bool dark=false;@override void initState(){super.initState();DB.dark().then((v){if(mounted)setState(()=>dark=v);});}void theme(bool v){setState(()=>dark=v);DB.setDark(v);}@override Widget build(BuildContext c)=>MaterialApp(debugShowCheckedModeBanner:false,title:'میراث ملک',locale:const Locale('fa'),supportedLocales:const[Locale('fa')],localizationsDelegates:GlobalMaterialLocalizations.delegates,themeMode:dark?ThemeMode.dark:ThemeMode.light,theme:ThemeData(useMaterial3:true,colorScheme:ColorScheme.fromSeed(seedColor:const Color(0xffb8860b))),darkTheme:ThemeData(useMaterial3:true,colorScheme:ColorScheme.fromSeed(seedColor:const Color(0xffd7aa4a),brightness:Brightness.dark)),home:Login(onTheme:theme));}}
Widget logo({double h=90})=>SvgPicture.asset('logo.svg',height:h,fit:BoxFit.contain);

class Login extends StatefulWidget{final void Function(bool) onTheme;const Login({super.key,required this.onTheme});@override State<Login>createState()=>_Login();}
class _Login extends State<Login>{final user=TextEditingController(),pass=TextEditingController();bool hide=true,busy=false;String err='';Future<void> go()async{setState(()=>busy=true);final list=await DB.users();User? found;for(final x in list){if(x.username==user.text.trim()){found=x;break;}}if(found==null||found.password!=hp(pass.text)){setState((){busy=false;err='نام کاربری یا رمز عبور اشتباه است';});return;}me=found;await DB.load();if(mounted)Navigator.pushReplacement(context,MaterialPageRoute(builder:(_)=>Dash(onTheme:widget.onTheme)));}@override Widget build(BuildContext c)=>Scaffold(body:Center(child:ConstrainedBox(constraints:const BoxConstraints(maxWidth:470),child:SingleChildScrollView(padding:const EdgeInsets.all(24),child:Column(children:[logo(h:125),const Text('میراث ملک',style:TextStyle(fontSize:32,fontWeight:FontWeight.bold)),const Text('سیستم مدیریت هوشمند دپارتمان املاک'),const SizedBox(height:5),const Text('مدیریت مهندس مجتبی صفری'),const Text('مدیر فروش خانم طهماسبی پور'),const SizedBox(height:24),TextField(controller:user,decoration:const InputDecoration(labelText:'نام کاربری',prefixIcon:Icon(Icons.person),border:OutlineInputBorder())),const SizedBox(height:12),TextField(controller:pass,obscureText:hide,decoration:InputDecoration(labelText:'رمز عبور',prefixIcon:const Icon(Icons.lock),border:const OutlineInputBorder(),suffixIcon:IconButton(onPressed:()=>setState(()=>hide=!hide),icon:Icon(hide?Icons.visibility:Icons.visibility_off)))),if(err.isNotEmpty)Padding(padding:const EdgeInsets.all(8),child:Text(err,style:TextStyle(color:Theme.of(c).colorScheme.error))),const SizedBox(height:16),SizedBox(width:double.infinity,height:52,child:FilledButton(onPressed:busy?null:go,child:Text(busy?'در حال ورود...':'ورود به سامانه'))),const SizedBox(height:10),const Text('رمز اولیه حساب‌های پیش‌فرض: 1234',style:TextStyle(fontSize:12))]))));}}

class Dash extends StatefulWidget{final void Function(bool) onTheme;const Dash({super.key,required this.onTheme});@override State<Dash>createState()=>_Dash();}
class _Dash extends State<Dash>{int tab=0;void refresh()=>setState((){});@override Widget build(BuildContext c){final pages=[const Home(),Properties(refresh:refresh),Clients(refresh:refresh),const Commission(),Meetings(refresh:refresh)];return Scaffold(appBar:AppBar(title:Row(children:[logo(h:36),const SizedBox(width:8),const Text('میراث ملک')]),actions:[IconButton(onPressed:()=>showDialog(context:c,builder:(_)=>Settings(onTheme:widget.onTheme)),icon:const Icon(Icons.settings))]),body:pages[tab],bottomNavigationBar:NavigationBar(selectedIndex:tab,onDestinationSelected:(i)=>setState(()=>tab=i),destinations:const[NavigationDestination(icon:Icon(Icons.dashboard),label:'خانه'),NavigationDestination(icon:Icon(Icons.home_work),label:'فایل‌ها'),NavigationDestination(icon:Icon(Icons.people),label:'مشتریان'),NavigationDestination(icon:Icon(Icons.calculate),label:'کمیسیون'),NavigationDestination(icon:Icon(Icons.event),label:'جلسات')]));}}

class Home extends StatelessWidget{const Home({super.key});@override Widget build(BuildContext c)=>ListView(padding:const EdgeInsets.all(16),children:[Text('سلام ${me?.name??''}',style:const TextStyle(fontSize:25,fontWeight:FontWeight.bold)),Text(me?.role??''),const SizedBox(height:18),Wrap(spacing:10,runSpacing:10,children:[box('فایل‌ها',props.length,Icons.home_work),box('مشتری‌ها',clients.length,Icons.people),box('جلسه‌ها',meetings.length,Icons.event)]),const SizedBox(height:18),Card(child:Padding(padding:const EdgeInsets.all(18),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:const[Text('مدیریت میراث ملک',style:TextStyle(fontSize:20,fontWeight:FontWeight.bold)),SizedBox(height:8),Text('مدیریت: مهندس مجتبی صفری'),Text('مدیر فروش: خانم طهماسبی پور'),Text('مدیر و مدیر فروش: دسترسی کامل'),Text('مشاور: مشاهده همه فایل‌ها؛ شماره و آدرس مالک دیگران مخفی')])))]);}
Widget box(String t,int n,IconData i)=>SizedBox(width:150,height:105,child:Card(child:Column(mainAxisAlignment:MainAxisAlignment.center,children:[Icon(i,size:30),Text(t),Text('$n',style:const TextStyle(fontSize:20,fontWeight:FontWeight.bold))])));}

class Properties extends StatefulWidget{final VoidCallback refresh;const Properties({super.key,required this.refresh});@override State<Properties>createState()=>_Properties();}
class _Properties extends State<Properties>{String filter='همه';final q=TextEditingController();final types=const['همه','آپارتمان','ویلا','تجاری','اداری','زمین','باغ','مشارکت','پیش‌فروش'];Future<void> add()async{await showDialog(context:context,builder:(_)=>PropertyForm(onSave:(p)async{props.add(p);await DB.saveProps();setState((){});}));}Future<void> edit(Property p)async{if(!manager&&p.agent!=me?.username)return;await showDialog(context:context,builder:(_)=>PropertyForm(initial:p,onSave:(x)async{final i=props.indexOf(p);if(i>=0)props[i]=x;await DB.saveProps();setState((){});}));}@override Widget build(BuildContext c){final list=props.where((p){final text='${p.code} ${p.title} ${p.type} ${p.area} ${p.price}'.toLowerCase();return(filter=='همه'||p.type==filter)&&text.contains(q.text.toLowerCase());}).toList();return Column(children:[Padding(padding:const EdgeInsets.all(12),child:Row(children:[Expanded(child:TextField(controller:q,onChanged:(_)=>setState((){}),decoration:const InputDecoration(labelText:'جستجوی فایل',prefixIcon:Icon(Icons.search),border:OutlineInputBorder()))),const SizedBox(width:7),IconButton.filled(onPressed:add,icon:const Icon(Icons.add))])),SingleChildScrollView(scrollDirection:Axis.horizontal,child:Row(children:types.map((x)=>Padding(padding:const EdgeInsets.all(3),child:ChoiceChip(label:Text(x),selected:filter==x,onSelected:(_)=>setState(()=>filter=x)))).toList())),Expanded(child:list.isEmpty?const Center(child:Text('فایلی ثبت نشده است')):ListView.builder(itemCount:list.length,itemBuilder:(_,i){final p=list[i];final own=manager||p.agent==me?.username;return Card(child:ListTile(title:Text('${p.code} - ${p.title}'),subtitle:Text(own?'${p.type} | ${p.area} متر | ${p.price}\nمالک: ${p.owner} | ${p.phone}\nآدرس: ${p.address}':'${p.type} | ${p.area} متر | ${p.price}\nمشاور: ${p.agent}\nشماره و آدرس مالک: مخفی'),isThreeLine:true,trailing:PopupMenuButton<String>(onSelected:(v){if(v=='edit')edit(p);if(v=='open'&&p.link.isNotEmpty)launchUrl(Uri.parse(p.link),mode:LaunchMode.externalApplication);},itemBuilder:(_)=>[if(own)const PopupMenuItem(value:'edit',child:Text('ویرایش')),if(p.link.isNotEmpty)const PopupMenuItem(value:'open',child:Text('لینک دیوار'))])));}))]);}}

class PropertyForm extends StatefulWidget{final Property? initial;final Future<void> Function(Property) onSave;const PropertyForm({super.key,this.initial,required this.onSave});@override State<PropertyForm>createState()=>_PropertyForm();}
class _PropertyForm extends State<PropertyForm>{late Map<String,TextEditingController> c;String type='آپارتمان';final types=const['آپارتمان','ویلا','تجاری','اداری','زمین','باغ','مشارکت','پیش‌فروش'];@override void initState(){super.initState();final p=widget.initial;final v={'code':p?.code??'','title':p?.title??'','address':p?.address??'','owner':p?.owner??'','phone':p?.phone??'','price':p?.price??'','area':p?.area??'','rooms':p?.rooms??'','year':p?.year??'','link':p?.link??'','desc':p?.desc??''};c={for(final e in v.entries)e.key:TextEditingController(text:e.value)};if(p!=null)type=p.type;}@override void dispose(){for(final x in c.values)x.dispose();super.dispose();}Widget f(String k,String l)=>Padding(padding:const EdgeInsets.only(bottom:8),child:TextField(controller:c[k],decoration:InputDecoration(labelText:l,border:const OutlineInputBorder())));Future<void> save()async{final p=Property(code:c['code']!.text.trim().isEmpty?'M-${DateTime.now().millisecondsSinceEpoch}':c['code']!.text.trim(),type:type,title:c['title']!.text.trim(),address:c['address']!.text.trim(),owner:c['owner']!.text.trim(),phone:c['phone']!.text.trim(),price:c['price']!.text.trim(),area:c['area']!.text.trim(),rooms:c['rooms']!.text.trim(),year:c['year']!.text.trim(),link:c['link']!.text.trim(),desc:c['desc']!.text.trim(),agent:widget.initial?.agent??me?.username??'');await widget.onSave(p);if(mounted)Navigator.pop(context);}@override Widget build(BuildContext cxt)=>AlertDialog(title:Text(widget.initial==null?'ثبت فایل ملک':'ویرایش فایل'),content:SizedBox(width:520,child:SingleChildScrollView(child:Column(children:[DropdownButtonFormField<String>(initialValue:type,items:types.map((x)=>DropdownMenuItem<String>(value:x,child:Text(x))).toList(),onChanged:(v){if(v!=null)setState(()=>type=v);},decoration:const InputDecoration(labelText:'نوع ملک',border:OutlineInputBorder())),const SizedBox(height:10),f('code','کد فایل'),f('title','عنوان'),f('address','آدرس مالک'),f('owner','نام مالک'),f('phone','شماره مالک'),f('price','قیمت'),f('area','متراژ'),f('rooms','تعداد خواب'),f('year','سال ساخت'),f('link','لینک دیوار'),f('desc','توضیحات')])),),actions:[TextButton(onPressed:()=>Navigator.pop(cxt),child:const Text('انصراف')),FilledButton(onPressed:save,child:const Text('ذخیره'))]);}}

class Clients extends StatefulWidget{final VoidCallback refresh;const Clients({super.key,required this.refresh});@override State<Clients>createState()=>_Clients();}
class _Clients extends State<Clients>{final c=TextEditingController();void add(){showDialog(context:context,builder:(_)=>AlertDialog(title:const Text('ثبت مشتری'),content:TextField(controller:c,decoration:const InputDecoration(labelText:'نام و شماره مشتری',border:OutlineInputBorder())),actions:[TextButton(onPressed:()=>Navigator.pop(context),child:const Text('انصراف')),FilledButton(onPressed:()async{if(c.text.trim().isNotEmpty){clients.add(c.text.trim());await DB.saveClients();setState((){});}if(mounted)Navigator.pop(context);},child:const Text('ذخیره'))]));}@override Widget build(BuildContext cxt)=>Column(children:[Padding(padding:const EdgeInsets.all(12),child:FilledButton.icon(onPressed:add,icon:const Icon(Icons.person_add),label:const Text('افزودن مشتری'))),Expanded(child:clients.isEmpty?const Center(child:Text('مشتری ثبت نشده است')):ListView.builder(itemCount:clients.length,itemBuilder:(_,i)=>ListTile(leading:const Icon(Icons.person),title:Text(clients[i]),trailing:IconButton(onPressed:()async{clients.removeAt(i);await DB.saveClients();setState((){});},icon:const Icon(Icons.delete_outline)))))]);}

class Meetings extends StatefulWidget{final VoidCallback refresh;const Meetings({super.key,required this.refresh});@override State<Meetings>createState()=>_Meetings();}
class _Meetings extends State<Meetings>{final c=TextEditingController();void add(){showDialog(context:context,builder:(_)=>AlertDialog(title:const Text('ثبت جلسه'),content:TextField(controller:c,maxLines:3,decoration:const InputDecoration(labelText:'تاریخ، ساعت و موضوع',border:OutlineInputBorder())),actions:[TextButton(onPressed:()=>Navigator.pop(context),child:const Text('انصراف')),FilledButton(onPressed:()async{if(c.text.trim().isNotEmpty){meetings.add(c.text.trim());await DB.saveMeetings();setState((){});}if(mounted)Navigator.pop(context);},child:const Text('ذخیره'))]));}@override Widget build(BuildContext cxt)=>Column(children:[Padding(padding:const EdgeInsets.all(12),child:FilledButton.icon(onPressed:add,icon:const Icon(Icons.add),label:const Text('ثبت جلسه'))),Expanded(child:meetings.isEmpty?const Center(child:Text('جلسه‌ای ثبت نشده است')):ListView.builder(itemCount:meetings.length,itemBuilder:(_,i)=>ListTile(leading:const Icon(Icons.event),title:Text(meetings[i]),trailing:IconButton(onPressed:()async{meetings.removeAt(i);await DB.saveMeetings();setState((){});},icon:const Icon(Icons.delete_outline)))))]);}

class Commission extends StatefulWidget{const Commission({super.key});@override State<Commission>createState()=>_Commission();}
class _Commission extends State<Commission>{final p=TextEditingController();double rate=.5,vat=10;@override Widget build(BuildContext c){final n=double.tryParse(p.text.replaceAll(',',''))??0;final fee=n*rate/100;final total=fee*(1+vat/100);return ListView(padding:const EdgeInsets.all(16),children:[const Text('محاسبه کمیسیون',style:TextStyle(fontSize:25,fontWeight:FontWeight.bold)),const SizedBox(height:15),TextField(controller:p,onChanged:(_)=>setState((){}),keyboardType:TextInputType.number,decoration:const InputDecoration(labelText:'قیمت معامله',border:OutlineInputBorder())),const SizedBox(height:12),DropdownButtonFormField<double>(initialValue:rate,items:const[DropdownMenuItem(value:.5,child:Text('۰٫۵ درصد')),DropdownMenuItem(value:1,child:Text('۱ درصد')),DropdownMenuItem(value:25,child:Text('۲۵ درصد'))],onChanged:(v){if(v!=null)setState(()=>rate=v);},decoration:const InputDecoration(labelText:'نرخ کمیسیون',border:OutlineInputBorder())),const SizedBox(height:12),DropdownButtonFormField<double>(initialValue:vat,items:const[DropdownMenuItem(value:0,child:Text('بدون مالیات')),DropdownMenuItem(value:10,child:Text('۱۰ درصد مالیات'))],onChanged:(v){if(v!=null)setState(()=>vat=v);},decoration:const InputDecoration(labelText:'مالیات',border:OutlineInputBorder())),const SizedBox(height:18),Card(child:Padding(padding:const EdgeInsets.all(18),child:Text('کمیسیون: ${fee.toStringAsFixed(0)}\nمبلغ نهایی: ${total.toStringAsFixed(0)}',style:const TextStyle(fontSize:20,fontWeight:FontWeight.bold))))]);}}

class Settings extends StatefulWidget{final void Function(bool) onTheme;const Settings({super.key,required this.onTheme});@override State<Settings>createState()=>_Settings();}
class _Settings extends State<Settings>{bool dark=false;@override void initState(){super.initState();DB.dark().then((v){if(mounted)setState(()=>dark=v);});}Future<void> changePass()async{final a=TextEditingController(),b=TextEditingController(),d=TextEditingController();await showDialog(context:context,builder:(_)=>AlertDialog(title:const Text('تغییر رمز عبور'),content:Column(mainAxisSize:MainAxisSize.min,children:[TextField(controller:a,obscureText:true,decoration:const InputDecoration(labelText:'رمز فعلی')),TextField(controller:b,obscureText:true,decoration:const InputDecoration(labelText:'رمز جدید')),TextField(controller:d,obscureText:true,decoration:const InputDecoration(labelText:'تکرار رمز جدید'))]),actions:[TextButton(onPressed:()=>Navigator.pop(context),child:const Text('انصراف')),FilledButton(onPressed:()async{final list=await DB.users();final x=list.firstWhere((z)=>z.username==me!.username);if(x.password==hp(a.text)&&b.text.isNotEmpty&&b.text==d.text){x.password=hp(b.text);await DB.saveUsers(list);me=x;if(mounted)Navigator.pop(context);}},child:const Text('ذخیره'))]));}Future<void> addUser()async{final a=TextEditingController(),b=TextEditingController(),d=TextEditingController();await showDialog(context:context,builder:(_)=>AlertDialog(title:const Text('افزودن مشاور'),content:Column(mainAxisSize:MainAxisSize.min,children:[TextField(controller:a,decoration:const InputDecoration(labelText:'نام کاربری')),TextField(controller:b,decoration:const InputDecoration(labelText:'نام مشاور')),TextField(controller:d,obscureText:true,decoration:const InputDecoration(labelText:'رمز اولیه'))]),actions:[TextButton(onPressed:()=>Navigator.pop(context),child:const Text('انصراف')),FilledButton(onPressed:()async{if(a.text.isEmpty||b.text.isEmpty||d.text.isEmpty)return;final list=await DB.users();list.add(User(username:a.text.trim(),name:b.text.trim(),role:'مشاور',password:hp(d.text)));await DB.saveUsers(list);if(mounted)Navigator.pop(context);},child:const Text('ثبت'))]));}@override Widget build(BuildContext c)=>AlertDialog(title:const Text('تنظیمات میراث ملک'),content:SizedBox(width:520,child:ListView(shrinkWrap:true,children:[logo(h:70),const ListTile(title:Text('مدیریت مهندس مجتبی صفری'),subtitle:Text('مدیر سامانه')),const ListTile(title:Text('مدیر فروش خانم طهماسبی پور')),SwitchListTile(value:dark,onChanged:(v){setState(()=>dark=v);widget.onTheme(v);},title:const Text('تم تاریک')),ListTile(leading:const Icon(Icons.lock_reset),title:const Text('تغییر رمز من'),onTap:changePass),if(manager)ListTile(leading:const Icon(Icons.person_add),title:const Text('افزودن مشاور'),onTap:addUser)])),actions:[TextButton(onPressed:()=>Navigator.pop(context),child:const Text('بستن'))]);}}
