import 'dart:convert';
import 'package:crypto/crypto.dart';
import 'package:flutter/material.dart';
import 'package:flutter_localizations/flutter_localizations.dart';
import 'package:flutter_svg/flutter_svg.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:url_launcher/url_launcher.dart';

void main()=>runApp(const MirathMelkApp());
String hash(String s)=>sha256.convert(utf8.encode(s)).toString();

class User{String username,name,role,password;User(this.username,this.name,this.role,this.password);Map<String,dynamic> toJson()=>{'u':username,'n':name,'r':role,'p':password};factory User.fromJson(Map<String,dynamic>j)=>User('${j['u']??''}','${j['n']??''}','${j['r']??'مشاور'}','${j['p']??''}');}
class Property{String code,type,title,address,owner,phone,price,area,rooms,year,link,agent;Property(this.code,this.type,this.title,this.address,this.owner,this.phone,this.price,this.area,this.rooms,this.year,this.link,this.agent);Map<String,dynamic>toJson()=>{'c':code,'t':type,'ti':title,'a':address,'o':owner,'ph':phone,'pr':price,'ar':area,'ro':rooms,'y':year,'l':link,'ag':agent};factory Property.fromJson(Map<String,dynamic>j)=>Property('${j['c']??''}','${j['t']??'آپارتمان'}','${j['ti']??''}','${j['a']??''}','${j['o']??''}','${j['ph']??''}','${j['pr']??''}','${j['ar']??''}','${j['ro']??''}','${j['y']??''}','${j['l']??''}','${j['ag']??''}');}
final properties=<Property>[];final clients=<String>[];final meetings=<String>[];User? current;bool get manager=>current?.role=='مدیر'||current?.role=='مدیر فروش';

class Store{static const uk='users_final',pk='props_final',ck='clients_final',mk='meetings_final',tk='theme_final';static Future<SharedPreferences>get prefs=>SharedPreferences.getInstance();static Future<List<User>>users()async{final p=await prefs;final raw=p.getString(uk);if(raw==null){final a=[User('admin','مهندس مجتبی صفری','مدیر',hash('1234')),User('sales','خانم طهماسبی پور','مدیر فروش',hash('1234')),User('moshaver1','مشاور اول','مشاور',hash('1234'))];await saveUsers(a);return a;}return(jsonDecode(raw)as List).map((e)=>User.fromJson(Map<String,dynamic>.from(e))).toList();}static Future<void>saveUsers(List<User>x)async=>(await prefs).setString(uk,jsonEncode(x.map((e)=>e.toJson()).toList()));static Future<void>load()async{final p=await prefs;try{properties..clear()..addAll((jsonDecode(p.getString(pk)??'[]')as List).map((e)=>Property.fromJson(Map<String,dynamic>.from(e))));}catch(_){properties.clear();}clients..clear()..addAll(p.getStringList(ck)??[]);meetings..clear()..addAll(p.getStringList(mk)??[]);}static Future<void>saveAll()async{final p=await prefs;await p.setString(pk,jsonEncode(properties.map((e)=>e.toJson()).toList()));await p.setStringList(ck,clients);await p.setStringList(mk,meetings);}static Future<bool>dark()async=>(await prefs).getBool(tk)??false;static Future<void>setDark(bool v)async=>(await prefs).setBool(tk,v);}

class MirathMelkApp extends StatefulWidget{const MirathMelkApp({super.key});@override State<MirathMelkApp>createState()=>_AppState();}
class _AppState extends State<MirathMelkApp>{bool dark=false;@override void initState(){super.initState();Store.dark().then((v){if(mounted)setState(()=>dark=v);});}@override Widget build(BuildContext c)=>MaterialApp(debugShowCheckedModeBanner:false,title:'میراث ملک',locale:const Locale('fa'),supportedLocales:const[Locale('fa')],localizationsDelegates:GlobalMaterialLocalizations.delegates,themeMode:dark?ThemeMode.dark:ThemeMode.light,theme:ThemeData(useMaterial3:true,colorScheme:ColorScheme.fromSeed(seedColor:const Color(0xffb8860b))),darkTheme:ThemeData(useMaterial3:true,colorScheme:ColorScheme.fromSeed(seedColor:const Color(0xffd7aa4a),brightness:Brightness.dark)),home:Login(onTheme:(v){setState(()=>dark=v);Store.setDark(v);}),);}
Widget logo({double h=90})=>SvgPicture.asset('logo.svg',height:h,fit:BoxFit.contain);

class Login extends StatefulWidget{final ValueChanged<bool>onTheme;const Login({super.key,required this.onTheme});@override State<Login>createState()=>_LoginState();}
class _LoginState extends State<Login>{final u=TextEditingController(),p=TextEditingController();bool hide=true,busy=false;String err='';Future<void>go()async{setState(()=>busy=true);final list=await Store.users();User? found;for(final x in list){if(x.username==u.text.trim()){found=x;break;}}if(found==null||found.password!=hash(p.text)){setState((){busy=false;err='نام کاربری یا رمز عبور اشتباه است';});return;}current=found;await Store.load();if(!mounted)return;Navigator.pushReplacement(context,MaterialPageRoute(builder:(_)=>Dashboard(onTheme:widget.onTheme)));}@override Widget build(BuildContext c)=>Scaffold(body:Center(child:ConstrainedBox(constraints:const BoxConstraints(maxWidth:470),child:SingleChildScrollView(padding:const EdgeInsets.all(24),child:Column(children:[logo(h:120),const Text('میراث ملک',style:TextStyle(fontSize:32,fontWeight:FontWeight.bold)),const Text('سیستم مدیریت هوشمند دپارتمان املاک'),const Text('مدیریت مهندس مجتبی صفری'),const Text('مدیر فروش خانم طهماسبی پور'),const SizedBox(height:24),TextField(controller:u,decoration:const InputDecoration(labelText:'نام کاربری',prefixIcon:Icon(Icons.person),border:OutlineInputBorder())),const SizedBox(height:12),TextField(controller:p,obscureText:hide,decoration:InputDecoration(labelText:'رمز عبور',prefixIcon:const Icon(Icons.lock),border:const OutlineInputBorder(),suffixIcon:IconButton(onPressed:()=>setState(()=>hide=!hide),icon:Icon(hide?Icons.visibility:Icons.visibility_off)))),if(err.isNotEmpty)Padding(padding:const EdgeInsets.all(8),child:Text(err,style:TextStyle(color:Theme.of(c).colorScheme.error))),const SizedBox(height:16),SizedBox(width:double.infinity,height:52,child:FilledButton(onPressed:busy?null:go,child:Text(busy?'در حال ورود...':'ورود به سامانه'))),const SizedBox(height:10),const Text('رمز اولیه: 1234',style:TextStyle(fontSize:12))]))));}}

class Dashboard extends StatefulWidget{final ValueChanged<bool>onTheme;const Dashboard({super.key,required this.onTheme});@override State<Dashboard>createState()=>_DashboardState();}
class _DashboardState extends State<Dashboard>{int index=0;@override Widget build(BuildContext c){final pages=<Widget>[const HomePage(),PropertiesPage(onChanged:()=>setState((){})),ClientsPage(onChanged:()=>setState((){})),const CommissionPage(),MeetingsPage(onChanged:()=>setState((){}))];return Scaffold(appBar:AppBar(title:Row(children:[logo(h:36),const SizedBox(width:8),const Text('میراث ملک')]),actions:[IconButton(onPressed:()=>showDialog(context:c,builder:(_)=>SettingsDialog(onTheme:widget.onTheme)),icon:const Icon(Icons.settings))]),body:pages[index],bottomNavigationBar:NavigationBar(selectedIndex:index,onDestinationSelected:(i)=>setState(()=>index=i),destinations:const[NavigationDestination(icon:Icon(Icons.dashboard),label:'خانه'),NavigationDestination(icon:Icon(Icons.home_work),label:'فایل‌ها'),NavigationDestination(icon:Icon(Icons.people),label:'مشتریان'),NavigationDestination(icon:Icon(Icons.calculate),label:'کمیسیون'),NavigationDestination(icon:Icon(Icons.event),label:'جلسات')]));}}

class HomePage extends StatelessWidget{const HomePage({super.key});@override Widget build(BuildContext c)=>ListView(padding:const EdgeInsets.all(16),children:[Text('سلام ${current?.name??''}',style:const TextStyle(fontSize:25,fontWeight:FontWeight.bold)),Text(current?.role??''),const SizedBox(height:18),Wrap(spacing:10,runSpacing:10,children:[stat('فایل‌ها',properties.length,Icons.home_work),stat('مشتری‌ها',clients.length,Icons.people),stat('جلسه‌ها',meetings.length,Icons.event)]),const SizedBox(height:18),Card(child:Padding(padding:const EdgeInsets.all(18),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:const[Text('مدیریت میراث ملک',style:TextStyle(fontSize:20,fontWeight:FontWeight.bold)),SizedBox(height:8),Text('مدیریت: مهندس مجتبی صفری'),Text('مدیر فروش: خانم طهماسبی پور'),Text('مدیر و مدیر فروش: دسترسی کامل'),Text('مشاور: مشاهده همه فایل‌ها؛ شماره و آدرس مالک دیگران مخفی')])))]);}
Widget stat(String t,int n,IconData i)=>SizedBox(width:150,height:105,child:Card(child:Column(mainAxisAlignment:MainAxisAlignment.center,children:[Icon(i,size:30),Text(t),Text('$n',style:const TextStyle(fontSize:20,fontWeight:FontWeight.bold))])));}

class PropertiesPage extends StatefulWidget{final VoidCallback onChanged;const PropertiesPage({super.key,required this.onChanged});@override State<PropertiesPage>createState()=>_PropertiesPageState();}
class _PropertiesPageState extends State<PropertiesPage>{String filter='همه';final search=TextEditingController();final types=const['همه','آپارتمان','ویلا','تجاری','اداری','زمین','باغ','مشارکت','پیش‌فروش'];Future<void>add()async{await showDialog(context:context,builder:(_)=>PropertyDialog(onSave:(p)async{properties.add(p);await Store.saveAll();setState((){});}));}Future<void>edit(Property p)async{if(!manager&&p.agent!=current?.username)return;await showDialog(context:context,builder:(_)=>PropertyDialog(initial:p,onSave:(x)async{final i=properties.indexOf(p);if(i>=0)properties[i]=x;await Store.saveAll();setState((){});}));}@override Widget build(BuildContext c){final list=properties.where((p){final q='${p.code} ${p.title} ${p.type} ${p.area} ${p.price}'.toLowerCase();return(filter=='همه'||p.type==filter)&&q.contains(search.text.toLowerCase());}).toList();return Column(children:[Padding(padding:const EdgeInsets.all(12),child:Row(children:[Expanded(child:TextField(controller:search,onChanged:(_)=>setState((){}),decoration:const InputDecoration(labelText:'جستجوی فایل',prefixIcon:Icon(Icons.search),border:OutlineInputBorder()))),const SizedBox(width:8),IconButton.filled(onPressed:add,icon:const Icon(Icons.add))])),SingleChildScrollView(scrollDirection:Axis.horizontal,child:Row(children:types.map((t)=>Padding(padding:const EdgeInsets.all(3),child:ChoiceChip(label:Text(t),selected:filter==t,onSelected:(_)=>setState(()=>filter=t)))).toList())),Expanded(child:list.isEmpty?const Center(child:Text('فایلی ثبت نشده است')):ListView.builder(itemCount:list.length,itemBuilder:(context,i){final p=list[i];final own=manager||p.agent==current?.username;return Card(child:ListTile(title:Text('${p.code} - ${p.title}'),subtitle:Text(own?'${p.type} | ${p.area} متر | ${p.price}\nمالک: ${p.owner} | ${p.phone}\nآدرس: ${p.address}':'${p.type} | ${p.area} متر | ${p.price}\nمشاور: ${p.agent}\nشماره و آدرس مالک: مخفی'),isThreeLine:true,trailing:PopupMenuButton<String>(onSelected:(v){if(v=='edit')edit(p);if(v=='open'&&p.link.isNotEmpty)launchUrl(Uri.parse(p.link),mode:LaunchMode.externalApplication);},itemBuilder:(context)=>[if(own)const PopupMenuItem(value:'edit',child:Text('ویرایش')),if(p.link.isNotEmpty)const PopupMenuItem(value:'open',child:Text('لینک دیوار'))])));}))]);}}

class PropertyDialog extends StatefulWidget{final Property? initial;final Future<void>Function(Property)onSave;const PropertyDialog({super.key,this.initial,required this.onSave});@override State<PropertyDialog>createState()=>_PropertyDialogState();}
class _PropertyDialogState extends State<PropertyDialog>{late final Map<String,TextEditingController>c;String type='آپارتمان';final types=const['آپارتمان','ویلا','تجاری','اداری','زمین','باغ','مشارکت','پیش‌فروش'];@override void initState(){super.initState();final p=widget.initial;final v=<String,String>{'code':p?.code??'','title':p?.title??'','address':p?.address??'','owner':p?.owner??'','phone':p?.phone??'','price':p?.price??'','area':p?.area??'','rooms':p?.rooms??'','year':p?.year??'','link':p?.link??''};c={for(final e in v.entries)e.key=TextEditingController(text:e.value)};if(p!=null)type=p.type;}@override void dispose(){for(final x in c.values)x.dispose();super.dispose();}Widget f(String k,String l)=>Padding(padding:const EdgeInsets.only(bottom:8),child:TextField(controller:c[k],decoration:InputDecoration(labelText:l,border:const OutlineInputBorder())));Future<void>save()async{final p=Property(c['code']!.text.trim().isEmpty?'M-${DateTime.now().millisecondsSinceEpoch}':c['code']!.text.trim(),type,c['title']!.text.trim(),c['address']!.text.trim(),c['owner']!.text.trim(),c['phone']!.text.trim(),c['price']!.text.trim(),c['area']!.text.trim(),c['rooms']!.text.trim(),c['year']!.text.trim(),c['link']!.text.trim(),widget.initial?.agent??current?.username??'');await widget.onSave(p);if(mounted)Navigator.pop(context);}@override Widget build(BuildContext c)=>AlertDialog(title:Text(widget.initial==null?'ثبت فایل ملک':'ویرایش فایل'),content:SizedBox(width:520,child:SingleChildScrollView(child:Column(children:[DropdownButtonFormField<String>(initialValue:type,items:types.map((x)=>DropdownMenuItem<String>(value:x,child:Text(x))).toList(),onChanged:(v){if(v!=null)setState(()=>type=v);},decoration:const InputDecoration(labelText:'نوع ملک',border:OutlineInputBorder())),const SizedBox(height:10),f('code','کد فایل'),f('title','عنوان'),f('address','آدرس مالک'),f('owner','نام مالک'),f('phone','شماره مالک'),f('price','قیمت'),f('area','متراژ'),f('rooms','تعداد خواب'),f('year','سال ساخت'),f('link','لینک دیوار')])),),actions:[TextButton(onPressed:()=>Navigator.pop(context),child:const Text('انصراف')),FilledButton(onPressed:save,child:const Text('ذخیره'))]);}}

class ClientsPage extends StatefulWidget{final VoidCallback onChanged;const ClientsPage({super.key,required this.onChanged});@override State<ClientsPage>createState()=>_ClientsPageState();}
class _ClientsPageState extends State<ClientsPage>{final c=TextEditingController();Future<void>add()async{await showDialog(context:context,builder:(_)=>AlertDialog(title:const Text('ثبت مشتری'),content:TextField(controller:c,decoration:const InputDecoration(labelText:'نام و شماره مشتری',border:OutlineInputBorder())),actions:[TextButton(onPressed:()=>Navigator.pop(context),child:const Text('انصراف')),FilledButton(onPressed:()async{if(c.text.trim().isNotEmpty){clients.add(c.text.trim());await Store.saveAll();setState((){});}if(mounted)Navigator.pop(context);},child:const Text('ذخیره'))]));}@override Widget build(BuildContext cxt)=>Column(children:[Padding(padding:const EdgeInsets.all(12),child:FilledButton.icon(onPressed:add,icon:const Icon(Icons.person_add),label:const Text('افزودن مشتری'))),Expanded(child:clients.isEmpty?const Center(child:Text('مشتری ثبت نشده است')):ListView.builder(itemCount:clients.length,itemBuilder:(context,i)=>ListTile(leading:const Icon(Icons.person),title:Text(clients[i]),trailing:IconButton(onPressed:()async{clients.removeAt(i);await Store.saveAll();setState((){});},icon:const Icon(Icons.delete_outline)))))]);}

class MeetingsPage extends StatefulWidget{final VoidCallback onChanged;const MeetingsPage({super.key,required this.onChanged});@override State<MeetingsPage>createState()=>_MeetingsPageState();}
class _MeetingsPageState extends State<MeetingsPage>{final c=TextEditingController();Future<void>add()async{await showDialog(context:context,builder:(_)=>AlertDialog(title:const Text('ثبت جلسه'),content:TextField(controller:c,maxLines:3,decoration:const InputDecoration(labelText:'تاریخ، ساعت و موضوع',border:OutlineInputBorder())),actions:[TextButton(onPressed:()=>Navigator.pop(context),child:const Text('انصراف')),FilledButton(onPressed:()async{if(c.text.trim().isNotEmpty){meetings.add(c.text.trim());await Store.saveAll();setState((){});}if(mounted)Navigator.pop(context);},child:const Text('ذخیره'))]));}@override Widget build(BuildContext cxt)=>Column(children:[Padding(padding:const EdgeInsets.all(12),child:FilledButton.icon(onPressed:add,icon:const Icon(Icons.add),label:const Text('ثبت جلسه'))),Expanded(child:meetings.isEmpty?const Center(child:Text('جلسه‌ای ثبت نشده است')):ListView.builder(itemCount:meetings.length,itemBuilder:(context,i)=>ListTile(leading:const Icon(Icons.event),title:Text(meetings[i]),trailing:IconButton(onPressed:()async{meetings.removeAt(i);await Store.saveAll();setState((){});},icon:const Icon(Icons.delete_outline)))))]);}

class CommissionPage extends StatefulWidget{const CommissionPage({super.key});@override State<CommissionPage>createState()=>_CommissionPageState();}
class _CommissionPageState extends State<CommissionPage>{final p=TextEditingController();double rate=.5,vat=10;@override Widget build(BuildContext c){final n=double.tryParse(p.text.replaceAll(',',''))??0;final fee=n*rate/100;final total=fee*(1+vat/100);return ListView(padding:const EdgeInsets.all(16),children:[const Text('محاسبه کمیسیون',style:TextStyle(fontSize:25,fontWeight:FontWeight.bold)),const SizedBox(height:15),TextField(controller:p,onChanged:(_)=>setState((){}),keyboardType:TextInputType.number,decoration:const InputDecoration(labelText:'قیمت معامله',border:OutlineInputBorder())),const SizedBox(height:12),DropdownButtonFormField<double>(initialValue:rate,items:const[DropdownMenuItem(value:.5,child:Text('۰٫۵ درصد')),DropdownMenuItem(value:1,child:Text('۱ درصد')),DropdownMenuItem(value:25,child:Text('۲۵ درصد'))],onChanged:(v){if(v!=null)setState(()=>rate=v);},decoration:const InputDecoration(labelText:'نرخ کمیسیون',border:OutlineInputBorder())),const SizedBox(height:12),DropdownButtonFormField<double>(initialValue:vat,items:const[DropdownMenuItem(value:0,child:Text('بدون مالیات')),DropdownMenuItem(value:10,child:Text('۱۰ درصد مالیات'))],onChanged:(v){if(v!=null)setState(()=>vat=v);},decoration:const InputDecoration(labelText:'مالیات',border:OutlineInputBorder())),const SizedBox(height:18),Card(child:Padding(padding:const EdgeInsets.all(18),child:Text('کمیسیون: ${fee.toStringAsFixed(0)}\nمبلغ نهایی: ${total.toStringAsFixed(0)}',style:const TextStyle(fontSize:20,fontWeight:FontWeight.bold))))]);}}

class SettingsDialog extends StatefulWidget{final ValueChanged<bool>onTheme;const SettingsDialog({super.key,required this.onTheme});@override State<SettingsDialog>createState()=>_SettingsDialogState();}
class _SettingsDialogState extends State<SettingsDialog>{bool dark=false;@override void initState(){super.initState();Store.dark().then((v){if(mounted)setState(()=>dark=v);});}Future<void>changePassword()async{final a=TextEditingController(),b=TextEditingController(),d=TextEditingController();await showDialog(context:context,builder:(_)=>AlertDialog(title:const Text('تغییر رمز عبور'),content:Column(mainAxisSize:MainAxisSize.min,children:[TextField(controller:a,obscureText:true,decoration:const InputDecoration(labelText:'رمز فعلی')),TextField(controller:b,obscureText:true,decoration:const InputDecoration(labelText:'رمز جدید')),TextField(controller:d,obscureText:true,decoration:const InputDecoration(labelText:'تکرار رمز جدید'))]),actions:[TextButton(onPressed:()=>Navigator.pop(context),child:const Text('انصراف')),FilledButton(onPressed:()async{final list=await Store.users();final u=list.firstWhere((x)=>x.username==current!.username);if(u.password==hash(a.text)&&b.text.isNotEmpty&&b.text==d.text){u.password=hash(b.text);await Store.saveUsers(list);current=u;if(mounted)Navigator.pop(context);}},child:const Text('ذخیره'))]));}Future<void>addConsultant()async{final a=TextEditingController(),b=TextEditingController(),d=TextEditingController();await showDialog(context:context,builder:(_)=>AlertDialog(title:const Text('افزودن مشاور'),content:Column(mainAxisSize:MainAxisSize.min,children:[TextField(controller:a,decoration:const InputDecoration(labelText:'نام کاربری')),TextField(controller:b,decoration:const InputDecoration(labelText:'نام مشاور')),TextField(controller:d,obscureText:true,decoration:const InputDecoration(labelText:'رمز اولیه'))]),actions:[TextButton(onPressed:()=>Navigator.pop(context),child:const Text('انصراف')),FilledButton(onPressed:()async{if(a.text.trim().isEmpty||b.text.trim().isEmpty||d.text.isEmpty)return;final list=await Store.users();list.add(User(a.text.trim(),b.text.trim(),'مشاور',hash(d.text)));await Store.saveUsers(list);if(mounted)Navigator.pop(context);},child:const Text('ثبت مشاور'))]));}@override Widget build(BuildContext c)=>AlertDialog(title:const Text('تنظیمات میراث ملک'),content:SizedBox(width:520,child:ListView(shrinkWrap:true,children:[logo(h:70),const ListTile(title:Text('مدیریت مهندس مجتبی صفری'),subtitle:Text('مدیر سامانه')),const ListTile(title:Text('مدیر فروش خانم طهماسبی پور')),SwitchListTile(value:dark,onChanged:(v){setState(()=>dark=v);widget.onTheme(v);},title:const Text('تم تاریک')),ListTile(leading:const Icon(Icons.lock_reset),title:const Text('تغییر رمز من'),onTap:changePassword),if(manager)ListTile(leading:const Icon(Icons.person_add),title:const Text('افزودن مشاور'),onTap:addConsultant)])),actions:[TextButton(onPressed:()=>Navigator.pop(context),child:const Text('بستن'))]);}}
