import 'dart:convert';
import 'package:crypto/crypto.dart';
import 'package:flutter/material.dart';
import 'package:flutter_localizations/flutter_localizations.dart';
import 'package:flutter_svg/flutter_svg.dart';
import 'package:shared_preferences/shared_preferences.dart';

const navy = Color(0xFF071827);
const navy2 = Color(0xFF102B40);
const gold = Color(0xFFD7A84A);
const page = Color(0xFFF5F7F9);
String hashPass(String s) => sha256.convert(utf8.encode(s)).toString();

class User { User(this.username,this.name,this.role,this.password); String username,name,role,password; Map<String,dynamic> toJson()=>{'u':username,'n':name,'r':role,'p':password}; factory User.fromJson(Map<String,dynamic> j)=>User('${j['u']}','${j['n']}','${j['r']}','${j['p']}'); }
class Property { Property({required this.code,required this.type,required this.title,required this.area,required this.price,required this.owner,required this.phone,required this.address,required this.agent}); String code,type,title,area,price,owner,phone,address,agent; Map<String,dynamic> toJson()=>{'c':code,'t':type,'ti':title,'a':area,'pr':price,'o':owner,'ph':phone,'ad':address,'ag':agent}; factory Property.fromJson(Map<String,dynamic> j)=>Property(code:'${j['c']}',type:'${j['t']}',title:'${j['ti']}',area:'${j['a']}',price:'${j['pr']}',owner:'${j['o']}',phone:'${j['ph']}',address:'${j['ad']}',agent:'${j['ag']}'); }
final properties=<Property>[]; final clients=<String>[]; final meetings=<String>[]; User? currentUser; bool get manager=>currentUser?.role=='مدیر'||currentUser?.role=='مدیر فروش';

class Store {
 static Future<SharedPreferences> get p=>SharedPreferences.getInstance();
 static Future<List<User>> users() async { final sp=await p; final raw=sp.getString('users'); if(raw==null){final list=[User('admin','مهندس مجتبی صفری','مدیر',hashPass('1234')),User('sales','خانم طهماسبی پور','مدیر فروش',hashPass('1234')),User('moshaver1','مشاور اول','مشاور',hashPass('1234'))]; await saveUsers(list); return list;} return (jsonDecode(raw) as List).map((e)=>User.fromJson(Map<String,dynamic>.from(e))).toList(); }
 static Future<void> saveUsers(List<User> u) async=>(await p).setString('users',jsonEncode(u.map((e)=>e.toJson()).toList()));
 static Future<void> load() async {final sp=await p; final raw=jsonDecode(sp.getString('properties')??'[]') as List; properties..clear()..addAll(raw.map((e)=>Property.fromJson(Map<String,dynamic>.from(e)))); clients..clear()..addAll(sp.getStringList('clients')??[]); meetings..clear()..addAll(sp.getStringList('meetings')??[]);}
 static Future<void> save() async {final sp=await p; await sp.setString('properties',jsonEncode(properties.map((e)=>e.toJson()).toList())); await sp.setStringList('clients',clients); await sp.setStringList('meetings',meetings);}
}

void main()=>runApp(const MirathApp());
class MirathApp extends StatefulWidget {const MirathApp({super.key}); @override State<MirathApp> createState()=>_MirathAppState();}
class _MirathAppState extends State<MirathApp>{bool dark=false; @override Widget build(BuildContext c)=>MaterialApp(debugShowCheckedModeBanner:false,title:'میراث ملک',locale:const Locale('fa'),supportedLocales:const[Locale('fa')],localizationsDelegates:GlobalMaterialLocalizations.delegates,theme:ThemeData(useMaterial3:true,scaffoldBackgroundColor:page,colorScheme:ColorScheme.fromSeed(seedColor:gold)),darkTheme:ThemeData(useMaterial3:true,brightness:Brightness.dark,colorScheme:ColorScheme.fromSeed(seedColor:gold,brightness:Brightness.dark)),themeMode:dark?ThemeMode.dark:ThemeMode.light,home:Login(onDark:(v)=>setState(()=>dark=v)));}
Widget logo({double size=70})=>SvgPicture.asset('logo.svg',height:size,width:size);

class Login extends StatefulWidget{const Login({super.key,required this.onDark});final ValueChanged<bool> onDark;@override State<Login> createState()=>_LoginState();}
class _LoginState extends State<Login>{final u=TextEditingController(),p=TextEditingController();String error='';bool hide=true;Future<void> enter()async{final list=await Store.users();User? found;for(final x in list){if(x.username==u.text.trim())found=x;}if(found==null||found!.password!=hashPass(p.text)){setState(()=>error='نام کاربری یا رمز عبور اشتباه است');return;}currentUser=found;await Store.load();if(!mounted)return;Navigator.pushReplacement(context,MaterialPageRoute(builder:(_)=>Dashboard(onDark:widget.onDark)));}@override Widget build(BuildContext c)=>Directionality(textDirection:TextDirection.rtl,child:Scaffold(body:Container(decoration:const BoxDecoration(gradient:LinearGradient(begin:Alignment.topCenter,end:Alignment.bottomCenter,colors:[navy,navy2,page])),child:Center(child:SingleChildScrollView(padding:const EdgeInsets.all(24),child:Card(elevation:18,shape:RoundedRectangleBorder(borderRadius:BorderRadius.circular(28)),child:Padding(padding:const EdgeInsets.all(28),child:ConstrainedBox(constraints:const BoxConstraints(maxWidth:430),child:Column(children:[logo(size:115),const Text('میراث ملک',style:TextStyle(fontSize:30,fontWeight:FontWeight.w900,color:navy)),const Text('مدیریت هوشمند املاک'),const SizedBox(height:8),const Text('مدیریت مهندس مجتبی صفری',style:TextStyle(color:gold,fontWeight:FontWeight.bold)),const Text('مدیر فروش خانم طهماسبی پور',style:TextStyle(fontWeight:FontWeight.bold)),const SizedBox(height:24),TextField(controller:u,decoration:const InputDecoration(labelText:'نام کاربری',prefixIcon:Icon(Icons.person),border:OutlineInputBorder())),const SizedBox(height:12),TextField(controller:p,obscureText:hide,decoration:InputDecoration(labelText:'رمز عبور',prefixIcon:const Icon(Icons.lock),suffixIcon:IconButton(onPressed:()=>setState(()=>hide=!hide),icon:Icon(hide?Icons.visibility:Icons.visibility_off)),border:const OutlineInputBorder())),if(error.isNotEmpty)Padding(padding:const EdgeInsets.only(top:10),child:Text(error,style:const TextStyle(color:Colors.red))),const SizedBox(height:18),SizedBox(width:double.infinity,height:52,child:FilledButton(onPressed:enter,style:FilledButton.styleFrom(backgroundColor:navy),child:const Text('ورود به سامانه'))),const SizedBox(height:8),const Text('رمز اولیه کاربران: 1234',style:TextStyle(fontSize:11,color:Colors.grey))]))))))));}
}

class Dashboard extends StatefulWidget{const Dashboard({super.key,required this.onDark});final ValueChanged<bool> onDark;@override State<Dashboard> createState()=>_DashboardState();}
class _DashboardState extends State<Dashboard>{int tab=0;void refresh()=>setState((){});@override Widget build(BuildContext c){final pages=[Home(onTab:(i)=>setState(()=>tab=i),refresh:refresh),Files(refresh:refresh),Clients(refresh:refresh),Meetings(refresh:refresh),const Commission()];return Directionality(textDirection:TextDirection.rtl,child:Scaffold(appBar:AppBar(backgroundColor:navy,foregroundColor:Colors.white,title:Row(children:[logo(size:48),const SizedBox(width:8),const Text('میراث ملک',style:TextStyle(fontWeight:FontWeight.w900))]),actions:[IconButton(onPressed:()=>showDialog(context:c,builder:(_)=>Settings(onDark:widget.onDark)),icon:const Icon(Icons.settings))]),body:pages[tab],bottomNavigationBar:NavigationBar(backgroundColor:navy,selectedIndex:tab,onDestinationSelected:(i)=>setState(()=>tab=i),destinations:const[NavigationDestination(icon:Icon(Icons.dashboard,color:Colors.white),label:'خانه'),NavigationDestination(icon:Icon(Icons.apartment,color:Colors.white),label:'فایل‌ها'),NavigationDestination(icon:Icon(Icons.people,color:Colors.white),label:'مشتریان'),NavigationDestination(icon:Icon(Icons.event,color:Colors.white),label:'جلسات'),NavigationDestination(icon:Icon(Icons.calculate,color:Colors.white),label:'کمیسیون')]));}}

class Home extends StatelessWidget{const Home({super.key,required this.onTab,required this.refresh});final ValueChanged<int> onTab;final VoidCallback refresh;@override Widget build(BuildContext c)=>ListView(padding:const EdgeInsets.all(18),children:[Container(padding:const EdgeInsets.all(22),decoration:BoxDecoration(borderRadius:BorderRadius.circular(24),gradient:const LinearGradient(colors:[navy,navy2])),child:Row(children:[CircleAvatar(backgroundColor:gold,radius:32,child:logo(size:48)),const SizedBox(width:14),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('سلام ${currentUser?.name??''}',style:const TextStyle(color:Colors.white,fontSize:21,fontWeight:FontWeight.bold)),const SizedBox(height:5),const Text('اعتماد، تجربه، آینده روشن در دستان شماست',style:TextStyle(color:Colors.white70))]))])),const SizedBox(height:18),GridView.count(shrinkWrap:true,physics:const NeverScrollableScrollPhysics(),crossAxisCount:2,crossAxisSpacing:12,mainAxisSpacing:12,childAspectRatio:1.45,children:[Tile('ثبت فایل جدید',Icons.add_home_work,Colors.green,()=>showDialog(context:c,builder:(_)=>PropertyDialog(onSave:(x)async{properties.add(x);await Store.save();refresh();}))),Tile('لیست فایل‌ها',Icons.apartment,Colors.blue,()=>onTab(1)),Tile('مشتریان',Icons.people,Colors.deepPurple,()=>onTab(2)),Tile('جلسات و قرارها',Icons.calendar_month,Colors.orange,()=>onTab(3)),Tile('مشاوران',Icons.groups,Colors.teal,()=>showDialog(context:c,builder:(_)=>const UsersDialog())),Tile('تنظیمات',Icons.settings,Colors.blueGrey,()=>showDialog(context:c,builder:(_)=>Settings(onDark:(_){ }))) ]),const SizedBox(height:18),Row(children:[Stat('فایل‌ها',properties.length),Stat('مشتریان',clients.length),Stat('جلسات',meetings.length)]),const SizedBox(height:12),const Card(child:Padding(padding:EdgeInsets.all(18),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('مدیریت میراث ملک',style:TextStyle(fontSize:19,fontWeight:FontWeight.bold)),SizedBox(height:8),Text('مدیریت مهندس مجتبی صفری  •  مدیر فروش خانم طهماسبی پور'),SizedBox(height:6),Text('مشاوران فایل‌ها را می‌بینند اما شماره و آدرس مالک دیگران برایشان مخفی است.')])))]);}
class Tile extends StatelessWidget{const Tile(this.title,this.icon,this.color,this.tap,{super.key});final String title;final IconData icon;final Color color;final VoidCallback tap;@override Widget build(BuildContext c)=>InkWell(onTap:tap,borderRadius:BorderRadius.circular(20),child:Container(decoration:BoxDecoration(color:color,borderRadius:BorderRadius.circular(20)),child:Column(mainAxisAlignment:MainAxisAlignment.center,children:[Icon(icon,color:Colors.white,size:34),const SizedBox(height:8),Text(title,style:const TextStyle(color:Colors.white,fontWeight:FontWeight.bold))])));}
class Stat extends StatelessWidget{const Stat(this.title,this.value,{super.key});final String title;final int value;@override Widget build(BuildContext c)=>Expanded(child:Card(child:Padding(padding:const EdgeInsets.all(14),child:Column(children:[Text(title,style:const TextStyle(color:Colors.grey)),Text('$value',style:const TextStyle(fontSize:24,fontWeight:FontWeight.bold,color:gold))]))));}

class Files extends StatefulWidget{const Files({super.key,required this.refresh});final VoidCallback refresh;@override State<Files> createState()=>_FilesState();}
class _FilesState extends State<Files>{String q='';@override Widget build(BuildContext c){final list=properties.where((p)=>'${p.code} ${p.title} ${p.area} ${p.price}'.contains(q)).toList();return Column(children:[Padding(padding:const EdgeInsets.all(16),child:Row(children:[Expanded(child:TextField(onChanged:(v)=>setState(()=>q=v),decoration:const InputDecoration(prefixIcon:Icon(Icons.search),labelText:'جستجوی فایل',border:OutlineInputBorder()))),const SizedBox(width:8),FilledButton(onPressed:()=>showDialog(context:c,builder:(_)=>PropertyDialog(onSave:(x)async{properties.add(x);await Store.save();widget.refresh();})),child:const Text('فایل جدید'))])),Expanded(child:list.isEmpty?const Center(child:Text('هنوز فایلی ثبت نشده')):ListView.builder(padding:const EdgeInsets.all(16),itemCount:list.length,itemBuilder:(_,i)=>PropertyCard(property:list[i]))) ]);}}
class PropertyCard extends StatelessWidget{const PropertyCard({super.key,required this.property});final Property property;@override Widget build(BuildContext c){final own=property.agent==currentUser?.name;final privateOk=manager||own;return Card(margin:const EdgeInsets.only(bottom:12),child:ListTile(leading:Container(width:58,height:58,decoration:BoxDecoration(color:navy,borderRadius:BorderRadius.circular(12)),child:const Icon(Icons.home,color:gold)),title:Text(property.title,style:const TextStyle(fontWeight:FontWeight.bold)),subtitle:Text('${property.area} متر  •  ${property.type}  •  ${property.price}'),trailing:IconButton(icon:const Icon(Icons.info_outline),onPressed:()=>showDialog(context:c,builder:(_)=>AlertDialog(title:Text(property.title),content:Text(privateOk?'مالک: ${property.owner}\nتلفن: ${property.phone}\nآدرس: ${property.address}':'اطلاعات مالک و آدرس برای شما مخفی است'),actions:[TextButton(onPressed:()=>Navigator.pop(c),child:const Text('بستن'))])))));}}

class PropertyDialog extends StatefulWidget{const PropertyDialog({super.key,required this.onSave});final Future<void> Function(Property) onSave;@override State<PropertyDialog> createState()=>_PropertyDialogState();}
class _PropertyDialogState extends State<PropertyDialog>{final code=TextEditingController(),title=TextEditingController(),area=TextEditingController(),price=TextEditingController(),owner=TextEditingController(),phone=TextEditingController(),address=TextEditingController();String type='آپارتمان';@override Widget build(BuildContext c)=>AlertDialog(title:const Text('ثبت فایل جدید'),content:SizedBox(width:480,child:SingleChildScrollView(child:Column(children:[field(code,'کد فایل'),field(title,'عنوان'),DropdownButtonFormField<String>(value:type,items:const['آپارتمان','ویلا','تجاری','اداری','زمین','باغ','مشارکت','پیش‌فروش'].map((x)=>DropdownMenuItem(value:x,child:Text(x))).toList(),onChanged:(v)=>setState(()=>type=v??type),decoration:const InputDecoration(labelText:'نوع ملک')),field(area,'متراژ'),field(price,'قیمت'),field(owner,'نام مالک'),field(phone,'شماره مالک'),field(address,'آدرس')])),actions:[TextButton(onPressed:()=>Navigator.pop(c),child:const Text('انصراف')),FilledButton(onPressed:()async{final p=Property(code:code.text,type:type,title:title.text,area:area.text,price:price.text,owner:owner.text,phone:phone.text,address:address.text,agent:currentUser?.name??'');await widget.onSave(p);if(c.mounted)Navigator.pop(c);},child:const Text('ثبت و ذخیره'))]);Widget field(TextEditingController x,String label)=>Padding(padding:const EdgeInsets.only(bottom:10),child:TextField(controller:x,decoration:InputDecoration(labelText:label,border:const OutlineInputBorder())));}

class Clients extends StatefulWidget{const Clients({super.key,required this.refresh});final VoidCallback refresh;@override State<Clients> createState()=>_ClientsState();}
class _ClientsState extends State<Clients>{final x=TextEditingController();@override Widget build(BuildContext c)=>Column(children:[Padding(padding:const EdgeInsets.all(16),child:Row(children:[Expanded(child:TextField(controller:x,decoration:const InputDecoration(labelText:'نام یا شماره مشتری',border:OutlineInputBorder()))),const SizedBox(width:8),FilledButton(onPressed:()async{if(x.text.trim().isEmpty)return;clients.add(x.text.trim());x.clear();await Store.save();setState((){});},child:const Text('ثبت'))])),Expanded(child:ListView(children:clients.map((e)=>ListTile(leading:const Icon(Icons.person),title:Text(e))).toList()))]);}
class Meetings extends StatefulWidget{const Meetings({super.key,required this.refresh});final VoidCallback refresh;@override State<Meetings> createState()=>_MeetingsState();}
class _MeetingsState extends State<Meetings>{final x=TextEditingController();@override Widget build(BuildContext c)=>Column(children:[Padding(padding:const EdgeInsets.all(16),child:Row(children:[Expanded(child:TextField(controller:x,decoration:const InputDecoration(labelText:'قرار یا جلسه جدید',border:OutlineInputBorder()))),const SizedBox(width:8),FilledButton(onPressed:()async{if(x.text.trim().isEmpty)return;meetings.add(x.text.trim());x.clear();await Store.save();setState((){});},child:const Text('ثبت'))])),Expanded(child:ListView(children:meetings.map((e)=>ListTile(leading:const Icon(Icons.event,color:gold),title:Text(e))).toList()))]);}
class Commission extends StatefulWidget{const Commission({super.key});@override State<Commission> createState()=>_CommissionState();}
class _CommissionState extends State<Commission>{final price=TextEditingController();double result=0;@override Widget build(BuildContext c)=>Padding(padding:const EdgeInsets.all(22),child:Card(child:Padding(padding:const EdgeInsets.all(20),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('محاسبه کمیسیون',style:TextStyle(fontSize:22,fontWeight:FontWeight.bold)),const SizedBox(height:16),TextField(controller:price,keyboardType:TextInputType.number,decoration:const InputDecoration(labelText:'مبلغ معامله',border:OutlineInputBorder())),const SizedBox(height:12),FilledButton(onPressed:(){setState(()=>result=(double.tryParse(price.text.replaceAll(',',''))??0)*0.005*1.1);},child:const Text('محاسبه ۰٫۵٪ + ۱۰٪ مالیات')),const SizedBox(height:16),Text('کمیسیون: ${result.toStringAsFixed(0)} تومان',style:const TextStyle(fontSize:18,fontWeight:FontWeight.bold,color:gold))]))));}
class UsersDialog extends StatefulWidget{const UsersDialog({super.key});@override State<UsersDialog> createState()=>_UsersDialogState();}
class _UsersDialogState extends State<UsersDialog>{@override Widget build(BuildContext c)=>AlertDialog(title:const Text('کاربران و مشاوران'),content:SizedBox(width:450,child:FutureBuilder<List<User>>(future:Store.users(),builder:(c,s){final list=s.data??[];return Column(mainAxisSize:MainAxisSize.min,children:list.map((u)=>ListTile(leading:Icon(u.role=='مشاور'?Icons.person:Icons.admin_panel_settings,color:gold),title:Text(u.name),subtitle:Text('${u.username} • ${u.role}'))).toList());})),actions:[TextButton(onPressed:()=>Navigator.pop(c),child:const Text('بستن'))]);}}
class Settings extends StatefulWidget{const Settings({super.key,required this.onDark});final ValueChanged<bool> onDark;@override State<Settings> createState()=>_SettingsState();}
class _SettingsState extends State<Settings>{bool dark=false;@override Widget build(BuildContext c)=>AlertDialog(title:const Text('تنظیمات سامانه'),content:SwitchListTile(title:const Text('حالت تیره'),value:dark,onChanged:(v){setState(()=>dark=v);widget.onDark(v);},secondary:const Icon(Icons.dark_mode)),actions:[TextButton(onPressed:()=>Navigator.pop(c),child:const Text('بستن'))]);}
