import React,{useEffect,useRef,useState} from 'react';
import {SafeAreaView,View,Text,StyleSheet,ScrollView,TextInput,Alert,Pressable} from 'react-native';
import {StatusBar} from 'expo-status-bar';
import {Ionicons} from '@expo/vector-icons';
import VoiceButton from './components/VoiceButton';
import QuestionCard from './components/QuestionCard';
import {QUESTIONS,PropertyRecord} from './lib/questions';
import {speak,startRecording,stopRecording} from './lib/voice';
import {usePropertyStore} from './store/usePropertyStore';
import {supabase} from './lib/supabase';
const empty={address:'',area:'',year:'',floor:'',amenities:'',deal:''};
export default function App(){
 const [screen,setScreen]=useState<'home'|'call'|'form'|'table'>('home'); const [active,setActive]=useState(false); const [q,setQ]=useState(0); const [form,setForm]=useState(empty); const [transcript,setTranscript]=useState(''); const rec=useRef<any>(null); const [audioUri,setAudioUri]=useState<string>();
 const {properties,hydrate,add}=usePropertyStore(); useEffect(()=>{hydrate()},[]);
 const ask=async(i:number)=>{setQ(i); await speak(QUESTIONS[i].prompt)};
 const begin=async()=>{try{setActive(true);setScreen('call');rec.current=await startRecording();await ask(0)}catch(e:any){Alert.alert('خطا',e.message);setActive(false)}};
 const end=async()=>{setActive(false);if(rec.current){try{setAudioUri(await stopRecording(rec.current))}catch{}}setScreen('form')};
 const next=async()=>{if(q<QUESTIONS.length-1)await ask(q+1);else await end()};
 const save=async()=>{if(!form.address.trim()){Alert.alert('اطلاعات ناقص','آدرس ملک را وارد کنید.');return}const p:PropertyRecord={id:Date.now().toString(),createdAt:new Date().toISOString(),...form,transcript,audioUri};await add(p);if(supabase){const {error}=await supabase.from('properties').insert({...p});if(error)Alert.alert('ذخیره ابری','ذخیره محلی انجام شد؛ ذخیره ابری خطا داشت.')}setForm(empty);setTranscript('');setScreen('table')};
 const set=(k:keyof typeof empty,v:string)=>setForm(x=>({...x,[k]:v}));
 return <SafeAreaView style={s.safe}><StatusBar style="dark"/><View style={s.header}><Text style={s.logo}>میراث ملک</Text><Text style={s.sub}>دستیار هوشمند ثبت فایل</Text></View><ScrollView contentContainerStyle={s.body}>
 {screen==='home'&&<><View style={s.hero}><Ionicons name="business" size={48} color="#166534"/><Text style={s.h1}>ثبت فایل با مکالمه هوشمند</Text><Text style={s.desc}>ربات شش سؤال اصلی را می‌پرسد و اطلاعات ملک را برای ثبت نهایی آماده می‌کند.</Text></View><VoiceButton active={false} onPress={begin}/><Pressable style={s.linkBtn} onPress={()=>setScreen('table')}><Ionicons name="list" size={22} color="#166534"/><Text style={s.linkText}>فایل‌های ثبت‌شده</Text></Pressable></>}
 {screen==='call'&&<><QuestionCard index={q} title={QUESTIONS[q].title} prompt={QUESTIONS[q].prompt}/><View style={s.calling}><Ionicons name="mic" size={32} color="#166534"/><Text style={s.callText}>در حال مکالمه…</Text><Text style={s.small}>پس از پاسخ مشتری، «سؤال بعدی» را بزنید.</Text></View><VoiceButton active={active} onPress={end}/><Pressable style={s.next} onPress={next}><Text style={s.nextText}>{q===5?'پایان و ثبت فرم':'سؤال بعدی'}</Text></Pressable></>}
 {screen==='form'&&<><Text style={s.h1}>فرم نهایی ملک</Text><Text style={s.desc}>پاسخ‌ها را بررسی و در صورت نیاز اصلاح کنید.</Text>{[['address','آدرس کامل ملک'],['area','متراژ زیربنا و زمین'],['year','سال ساخت'],['floor','طبقه و تعداد واحد'],['amenities','امکانات'],['deal','نوع معامله و مبلغ']].map(([k,l])=><View key={k} style={s.field}><Text style={s.label}>{l}</Text><TextInput value={form[k as keyof typeof empty]} onChangeText={v=>set(k as keyof typeof empty,v)} style={s.input} placeholder="وارد کنید…" textAlign="right"/></View>)}<Text style={s.label}>متن پیاده‌سازی‌شده / یادداشت</Text><TextInput value={transcript} onChangeText={setTranscript} multiline style={[s.input,{height:110,textAlignVertical:'top'}]}/><Pressable style={s.save} onPress={save}><Text style={s.saveText}>ذخیره در دیتابیس</Text></Pressable></>}
 {screen==='table'&&<><View style={s.rowTop}><Text style={s.h1}>فایل‌های ثبت‌شده</Text><Pressable onPress={()=>setScreen('home')}><Text style={s.back}>ثبت فایل جدید</Text></Pressable></View>{properties.length===0?<Text style={s.empty}>هنوز فایلی ثبت نشده است.</Text>:properties.map(p=><View key={p.id} style={s.item}><Text style={s.itemTitle}>{p.address}</Text><Text style={s.itemLine}>متراژ: {p.area||'—'} | سال ساخت: {p.year||'—'}</Text><Text style={s.itemLine}>طبقه/واحد: {p.floor||'—'}</Text><Text style={s.itemLine}>امکانات: {p.amenities||'—'}</Text><Text style={s.itemLine}>معامله: {p.deal||'—'}</Text></View>)}<Text style={s.jsonTitle}>JSON</Text><Text style={s.json}>{JSON.stringify(properties,null,2)}</Text></>}
 </ScrollView></SafeAreaView>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:'#f5f7f5'},header:{paddingHorizontal:20,paddingTop:18,paddingBottom:10,backgroundColor:'#fff'},logo:{fontSize:28,fontWeight:'900',color:'#14532d',textAlign:'right'},sub:{fontSize:13,color:'#6b7280',textAlign:'right',marginTop:2},body:{padding:20,paddingBottom:50},hero:{backgroundColor:'#ecfdf5',borderRadius:28,padding:24,alignItems:'center',marginTop:8},h1:{fontSize:25,fontWeight:'900',color:'#111827',textAlign:'right',marginTop:10},desc:{fontSize:16,lineHeight:27,color:'#4b5563',textAlign:'right',marginTop:8},linkBtn:{height:58,borderRadius:18,backgroundColor:'#fff',alignItems:'center',justifyContent:'center',flexDirection:'row',gap:8},linkText:{fontSize:16,fontWeight:'800',color:'#166534'},calling:{backgroundColor:'#fff',borderRadius:22,padding:22,alignItems:'center',marginTop:18},callText:{fontSize:20,fontWeight:'800',marginTop:8},small:{fontSize:14,color:'#6b7280',marginTop:5},next:{height:58,borderRadius:18,backgroundColor:'#166534',alignItems:'center',justifyContent:'center'},nextText:{color:'#fff',fontSize:18,fontWeight:'800'},field:{marginTop:15},label:{fontSize:15,fontWeight:'800',color:'#374151',marginBottom:7,textAlign:'right'},input:{backgroundColor:'#fff',borderRadius:16,borderWidth:1,borderColor:'#e5e7eb',padding:15,fontSize:16},save:{height:60,borderRadius:18,backgroundColor:'#14532d',alignItems:'center',justifyContent:'center',marginTop:22},saveText:{color:'#fff',fontSize:18,fontWeight:'900'},rowTop:{flexDirection:'row',alignItems:'center',justifyContent:'space-between'},back:{color:'#166534',fontWeight:'800'},empty:{textAlign:'center',color:'#6b7280',padding:30},item:{backgroundColor:'#fff',borderRadius:20,padding:18,marginTop:14},itemTitle:{fontSize:19,fontWeight:'900',textAlign:'right'},itemLine:{fontSize:14,color:'#4b5563',textAlign:'right',marginTop:5},jsonTitle:{fontSize:20,fontWeight:'900',marginTop:25,textAlign:'right'},json:{backgroundColor:'#111827',color:'#fff',padding:15,borderRadius:16,fontSize:11}});